#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo '🏗️👷 Styling, testing and building your project before committing'

# Check ESLint AirBnb Standards
npm run lint ||
(
    echo '🙈👷🔨❌ Yoo, your code looks disgusting. Check linter 🙈👷🔨❌
          Run npm run lint, add changes and try commit again.';
    false;
)

# Check ESLint Standards
npm run type-check ||
(
        echo '😤🏀👋😤 Yooo, Type check failed! Fix it and try to commit again  😤🏀👋😤'
        false;
)

# If everything passes... Now we can commit
# echo '🤔🤔🤔🤔... Alright... Code looks good to me... Trying to build now. 🤔🤔🤔🤔'

# npm run build ||
# (
#    echo '❌👷🔨❌ Better call Bob... Because your build failed ❌👷🔨❌
#            Next build failed: View the errors above to see why.
#    '
#    false;
#)

# If everything passes... Now we can commit
echo '🎉✨🚀 You win this time... I am committing this now. 🏄‍♂️🍻🌕'


npx lint-staged
